#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSegmentedControl.Resource", IsApplication=false)]

namespace AndroidSegmentedControl
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public static int awesome_text = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int sc_border_width = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int sc_checked_text_color = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int sc_corner_radius = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int sc_tint_color = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int sc_unchecked_tint_color = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int radio_button_selected_color = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int radio_button_unselected_color = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int radio_button_conner_radius = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int radio_button_stroke_border = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int button_text_color = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int radio_checked = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int radio_unchecked = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int RadioButton = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AwesomeRadioButton = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int AwesomeRadioButton_awesome_text = 0;
			
			public static int[] SegmentedGroup = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int SegmentedGroup_sc_border_width = 1;
			
			// aapt resource value: 3
			public static int SegmentedGroup_sc_checked_text_color = 3;
			
			// aapt resource value: 0
			public static int SegmentedGroup_sc_corner_radius = 0;
			
			// aapt resource value: 2
			public static int SegmentedGroup_sc_tint_color = 2;
			
			// aapt resource value: 4
			public static int SegmentedGroup_sc_unchecked_tint_color = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
